services:
    email_change_password:
        class: Fulgurio\UserBundle\EventListener\EmailChangePasswordListener
        tags:
            - { name: "kernel.event_subscriber" }
        arguments: [ "@fulgurio_user.mailer" ]
