services:
    fulgurio_user.registration_listener:
        class: Fulgurio\UserBundle\EventListener\RegistrationListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_subscriber }