services:
    fulgurio_user.registration_listener:
        class: Fulgurio\UserBundle\EventListener\RegistrationListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_subscriber }
    fulgurio_user.mailer:
        class: Fulgurio\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            -
                template:
                    change_password: %fulgurio_user.change_password.email.template%
                    unsubscribe:     %fulgurio_user.unsubscribe.email.template%
                    ban:             %fulgurio_user.ban.email.template%
                    unban:           %fulgurio_user.unban.email.template%
                from_email:
                    change_password: %fulgurio_user.change_password.email.from_email%
                    unsubscribe:     %fulgurio_user.unsubscribe.email.from_email%
                    ban:             %fulgurio_user.ban.email.from_email%
                enabled:
                    unsubscribe:     %fulgurio_user.unsubscribe.email.enabled%
                    ban:             %fulgurio_user.ban.email.enabled%
