<?php

namespace Fulgurio\UserBundle\Repository;

use Fulgurio\UserBundle\Repository\UserRepository;

/**
 * UserGravatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Vincent GUERARD <v.guerard@fulgurio.net>
 */
class UserGravatarRepository extends UserRepository
{
    /**
     * Class name of the returned entities
     * @var string
     */
    protected $userEntityName = 'FulgurioUserBundle:UserGravatar';
}
